baseURL = "https://metricrule.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "MetricRule"
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© MetricRule"
description = "ML model monitoring in production"
favicon = "images/favicon.png"
hidedesignbyline = false
images = []
title = "MetricRule Landing Page"
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
