baseURL = "https://metricrule.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "MetricRule - ML monitoring"
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© MetricRule"
description = "Open source ML model monitoring in production"
favicon = "images/favicon.png"
hidedesignbyline = false
images = []
title = "MetricRule - ML monitoring"
[params.meta]
keywords = "ml-monitoring, tensorflow, observability, real-time, open-source, production, deploy, serving"
